[colors]
wallpaper = "bg-karina-skrypnik.jpg"
background = "#17191a"
foreground = "#f1f5f4"
accent = "#6e9e9a"
status_accent = "#6e9e9a"
muted = "#778486"
border_normal = "#4f7675"
border_focused = "#9cc3c0"
urgent = "#ff3b30"
status_foreground = "#dde6e5"
battery_urgent = "#cc0a0a"
battery_warning = "#d9b000"
