[rpool/ROOT]
	use_template = system
	recursive = yes
[rpool/dockerdisk]
	use_template = docker
[rpool/USERDATA]
	use_template = data
	recursive = yes

#############################
# templates below this line #
#############################

[template_system]
	frequently = 0
	hourly = 0
	daily = 15
	monthly = 3
	yearly = 1
	autosnap = yes
	autoprune = yes

[template_docker]
	frequently = 0
	hourly = 0
	daily = 7
	monthly = 1
	yearly = 0
	autosnap = yes
	autoprune = yes

[template_data]
	frequently = 0
	hourly = 36
	daily = 30
	monthly = 3
	yearly = 1
	autosnap = yes
	autoprune = yes
